// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx';
import * as $_app from './routes/_app.tsx';
import * as $animated_image from './routes/animated-image.tsx';
import * as $boucing_ball from './routes/boucing-ball.tsx';
import * as $chess from './routes/chess.tsx';
import * as $index from './routes/index.tsx';
import * as $overlap from './routes/overlap.tsx';
import * as $pixel_painting from './routes/pixel-painting.tsx';
import * as $AnimatedImage from './islands/AnimatedImage.tsx';
import * as $Body from './islands/Body.tsx';
import * as $BouncingBall from './islands/BouncingBall.tsx';
import * as $Canvas from './islands/Canvas.tsx';
import * as $Chess from './islands/Chess.tsx';
import * as $Circle from './islands/Circle.tsx';
import * as $CircleImage from './islands/CircleImage.tsx';
import * as $Intro from './islands/Intro.tsx';
import * as $Overlap from './islands/Overlap.tsx';
import * as $PixelPainting from './islands/PixelPainting.tsx';
import type { Manifest } from '$fresh/server.ts';

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/_app.tsx': $_app,
    './routes/animated-image.tsx': $animated_image,
    './routes/boucing-ball.tsx': $boucing_ball,
    './routes/chess.tsx': $chess,
    './routes/index.tsx': $index,
    './routes/overlap.tsx': $overlap,
    './routes/pixel-painting.tsx': $pixel_painting,
  },
  islands: {
    './islands/AnimatedImage.tsx': $AnimatedImage,
    './islands/Body.tsx': $Body,
    './islands/BouncingBall.tsx': $BouncingBall,
    './islands/Canvas.tsx': $Canvas,
    './islands/Chess.tsx': $Chess,
    './islands/Circle.tsx': $Circle,
    './islands/CircleImage.tsx': $CircleImage,
    './islands/Intro.tsx': $Intro,
    './islands/Overlap.tsx': $Overlap,
    './islands/PixelPainting.tsx': $PixelPainting,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
